## Automated Hyperparameter Selection 

This tutorial demonstrates how to automatically select optimal Gaussian Process hyperparameters for your surrogate model by testing multiple configurations and choosing the one with the best test set performance.

### Why This Matters

GP surrogate model performance is highly sensitive to:
- **Kernel choice** (ExpSquared, Matern32, Matern52, etc.)
- **Data scaling** (no scaling, MinMax, StandardScaler)
- **Other hyperparameters** (white noise, amplitude, length scales)

Rather than manually tuning these, we can systematically test combinations and select the best configuration based on test set mean squared error (MSE).

### Step 1: Import Required Libraries

Import `alabi` and its submodules along with standard scientific computing libraries.

In [1]:
import alabi
import alabi.utility as ut
import alabi.benchmarks as bm
from alabi.core import SurrogateModel

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from itertools import product

np.random.seed(101)

### Step 2: Define Problem and Base Configuration

Set up the benchmark problem (eggbox function) and define a base configuration for GP hyperparameters. These settings will be partially overridden when we test different combinations.

**Key parameters:**
- `ninit`: Number of initial training points
- `niter`: Number of active learning iterations
- `ncore`: Number of CPU cores for parallel evaluation (use 1 if experiencing multiprocessing issues)
- `white_noise`: Log-scale white noise parameter (increase if you see positive definiteness errors)

In [2]:
ninit = 50
niter = 100
basedir = "demo"
kernel = "ExpSquaredKernel"
benchmark = "rosenbrock"
savedir = f"{basedir}/{benchmark}/{kernel}/{ninit}_{niter}"

gp_kwargs = {"kernel": kernel, 
             "fit_amp": True, 
             "fit_mean": True, 
             "fit_white_noise": False, 
             "white_noise": -12,
             "gp_opt_method": "l-bfgs-b",
             "hyperopt_method": "cv",
             "cv_folds": 8,
             "gp_amp_rng": [-1,1],
             "gp_scale_rng": [-2,2],
             "theta_scaler": alabi.no_scaler,
             "y_scaler": alabi.no_scaler}
    
sm = SurrogateModel(lnlike_fn=bm.eggbox["fn"], 
                    bounds=bm.eggbox["bounds"], 
                    savedir=savedir,
                    ncore=8, 
                    pool_method="forkserver",
                    verbose=True)

sm.init_samples(ntrain=ninit, ntest=1000, sampler="sobol")

  0%|          | 0/50 [00:00<?, ?it/s]

  2%|▏         | 1/50 [00:01<01:35,  1.94s/it]

100%|██████████| 50/50 [00:02<00:00, 24.93it/s]

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 1/1000 [00:01<30:32,  1.83s/it]

  0%|          | 2/1000 [00:02<14:59,  1.11it/s]

100%|██████████| 1000/1000 [00:02<00:00, 478.92it/s]

### Step 3: Create Hyperparameter Grid

Generate all combinations of the hyperparameters we want to test:
- **Kernels**: Different covariance functions capture different smoothness assumptions
- **Theta scaler**: How to scale input parameters
- **Y scaler**: How to scale output values

The `dict_to_combinations` function creates a Cartesian product of all options.

In [3]:
def dict_to_combinations(options_dict):
    keys = options_dict.keys()
    values = options_dict.values()
    return [dict(zip(keys, combo)) for combo in product(*values)]

def combinations_to_dict(combinations):
    result = {key: [] for key in combinations[0].keys()}
    for combo in combinations:
        for key, value in combo.items():
            result[key].append(value)
    return result

gp_kwarg_options = {"kernel": ["ExpSquaredKernel", "Matern32Kernel", "Matern52Kernel"],
                    "theta_scaler": [ut.no_scaler, preprocessing.MinMaxScaler(), preprocessing.StandardScaler()],
                    "y_scaler": [ut.no_scaler, preprocessing.MinMaxScaler(), preprocessing.StandardScaler()]}

variable_settings = dict_to_combinations(gp_kwarg_options)
print(len(variable_settings), "combinations to test")

# get a list of dictionaries with all combinations of settings, where each dictionary is a copy of the original gp_kwargs with the variable settings updated
setting_combos = []
for settings in variable_settings:
    new_settings = gp_kwargs.copy()
    for key in settings.keys():
        new_settings[key] = settings[key]
    setting_combos.append(new_settings)

27 combinations to test

### Step 4: Test All Hyperparameter Combinations

Loop through all combinations and fit a GP for each. The `init_gp` method returns the test set MSE, which we use to evaluate performance.

**Note:** This can take several minutes depending on the number of combinations and problem dimensionality. Use `try/except` to handle configurations that fail to converge.

In [4]:
for ii in range(len(setting_combos)):
    try:
        test_mse = sm.init_gp(**setting_combos[ii], overwrite=True)
    except:
        test_mse = np.nan
    setting_combos[ii]["test_mse"] = test_mse

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:53,  1.75s/candidate]

Evaluating candidates:   3%|▎         | 3/100 [00:01<00:48,  1.98candidate/s]

Evaluating candidates:   5%|▌         | 5/100 [00:01<00:25,  3.65candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:02<00:00, 49.37candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  64%|██████▍   | 32/50 [00:00<00:00, 316.52candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 349.64candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 370.16candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<03:00,  1.83s/candidate]

Evaluating candidates:   7%|▋         | 7/100 [00:01<00:19,  4.73candidate/s]

Evaluating candidates:  98%|█████████▊| 98/100 [00:02<00:00, 87.46candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:02<00:00, 48.25candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  58%|█████▊    | 29/50 [00:00<00:00, 268.29candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 324.10candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 341.58candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:57,  1.79s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 55.75candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:   8%|▊         | 4/50 [00:00<00:01, 32.73candidate/s]

Stage 2 candidates:  48%|████▊     | 24/50 [00:00<00:00, 118.67candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 169.15candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 346.52candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:55,  1.77s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 56.53candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  84%|████████▍ | 42/50 [00:00<00:00, 361.33candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 369.12candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 254.77candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:02<03:54,  2.37s/candidate]

Evaluating candidates:   2%|▏         | 2/100 [00:04<03:35,  2.20s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:04<00:00, 22.46candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  12%|█▏        | 6/50 [00:00<00:00, 53.47candidate/s]

Stage 2 candidates:  34%|███▍      | 17/50 [00:00<00:00, 84.25candidate/s]

Stage 2 candidates:  52%|█████▏    | 26/50 [00:00<00:00, 76.45candidate/s]

Stage 2 candidates:  80%|████████  | 40/50 [00:00<00:00, 98.62candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 96.98candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates:  24%|██▍       | 6/25 [00:00<00:00, 47.46candidate/s]

Stage 3 candidates:  72%|███████▏  | 18/25 [00:00<00:00, 75.72candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 80.01candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:03<06:35,  4.00s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:04<00:00, 24.78candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  92%|█████████▏| 46/50 [00:00<00:00, 447.19candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 466.53candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 518.84candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.19s/candidate]

Evaluating candidates:  82%|████████▏ | 82/100 [00:01<00:00, 86.03candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.91candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 618.82candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 578.64candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:06,  1.28s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.92candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 589.45candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 509.16candidate/s]

Initialized GP with squared exponential kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  88%|████████▊ | 88/100 [00:01<00:00, 92.64candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.94candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 630.86candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 567.32candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 79.49candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 677.41candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 583.29candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates:  71%|███████   | 71/100 [00:01<00:00, 75.16candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.02candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 644.72candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 551.14candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:00,  1.21s/candidate]

Evaluating candidates:  80%|████████  | 80/100 [00:01<00:00, 83.55candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.42candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 712.30candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 496.98candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:51,  1.12s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 82.25candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 755.55candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 620.01candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  93%|█████████▎| 93/100 [00:01<00:00, 98.03candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.91candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 621.63candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 589.35candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:01,  1.23s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 78.91candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 633.92candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 685.42candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.14s/candidate]

Evaluating candidates:   6%|▌         | 6/100 [00:01<00:14,  6.31candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 80.14candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 614.09candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 710.13candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates:  99%|█████████▉| 99/100 [00:01<00:00, 104.86candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.75candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 608.64candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 506.75candidate/s]

Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.15s/candidate]

Evaluating candidates:   8%|▊         | 8/100 [00:01<00:11,  8.13candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.29candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 639.65candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 589.82candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.17s/candidate]

Evaluating candidates:   3%|▎         | 3/100 [00:01<00:33,  2.92candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.33candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 680.87candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 677.76candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.15s/candidate]

Evaluating candidates:  54%|█████▍    | 54/100 [00:01<00:00, 59.38candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.47candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 709.46candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 517.64candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.16s/candidate]

Evaluating candidates:  52%|█████▏    | 52/100 [00:01<00:00, 56.63candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.33candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 783.73candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 713.70candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 79.38candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 625.81candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 709.58candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.17s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 108.28candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 78.57candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 656.46candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 563.00candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.17s/candidate]

Evaluating candidates:  89%|████████▉ | 89/100 [00:01<00:00, 95.90candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.41candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 652.60candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 536.49candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.13s/candidate]

Evaluating candidates:  84%|████████▍ | 84/100 [00:01<00:00, 93.39candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 79.72candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 655.45candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 569.79candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:04,  1.26s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.29candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 636.96candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 631.50candidate/s]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.15s/candidate]

Evaluating candidates:   5%|▌         | 5/100 [00:01<00:18,  5.15candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.89candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 618.06candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 615.41candidate/s]

### Step 5: Analyze Results

Convert results to a pandas DataFrame and inspect the top-performing configurations. Lower test MSE indicates better generalization performance.

In [5]:
results = pd.DataFrame(data=combinations_to_dict(setting_combos))
top_fits = results.sort_values("test_mse").head(5)
top_fits

,kernel,fit_amp,fit_mean,fit_white_noise,white_noise,gp_opt_method,hyperopt_method,cv_folds,gp_amp_rng,gp_scale_rng,theta_scaler,y_scaler,test_mse
25,Matern52Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),MinMaxScaler(),3014.105741
17,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),StandardScaler(),3085.244354
13,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",MinMaxScaler(),MinMaxScaler(),3262.803131
16,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),MinMaxScaler(),3274.704553
9,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",no_scaler,no_scaler,3300.396040

### Step 6: Extract Best Configuration

Identify the hyperparameter configuration with the lowest test MSE. This will be used for active learning.

In [6]:
best_gp_results = results[results["test_mse"] == results["test_mse"].min()]
best_gp_results

,kernel,fit_amp,fit_mean,fit_white_noise,white_noise,gp_opt_method,hyperopt_method,cv_folds,gp_amp_rng,gp_scale_rng,theta_scaler,y_scaler,test_mse
25,Matern52Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),MinMaxScaler(),3014.105741

### Step 7: Run Active Learning

Use the optimal GP configuration for active learning. The BAPE (Bayesian Active Posterior Estimation) algorithm iteratively selects new training points to improve the surrogate model.

**Key active learning parameters:**
- `algorithm`: Acquisition function ("bape", "agp", or "jones")
- `gp_opt_freq`: How often to reoptimize GP hyperparameters during training
- `obj_opt_method`: Optimization method for acquisition function
- `nopt`: Number of optimization restarts for acquisition function

In [7]:
best_gp_kwargs = best_gp_results[gp_kwargs.keys()].to_dict(orient="records")[0]

al_kwargs = {"algorithm": "bape", 
             "gp_opt_freq": 20, 
             "obj_opt_method": "nelder-mead", 
             "nopt": 6}

sm.init_gp(**best_gp_kwargs, overwrite=True)
sm.active_train(niter=200, **al_kwargs)

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates:  68%|██████▊   | 68/100 [00:01<00:00, 72.03candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.46candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 579.97candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 511.58candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  1%|          | 2/200 [00:00<00:10, 19.06it/s]

  2%|▏         | 4/200 [00:00<00:10, 18.78it/s]

  4%|▎         | 7/200 [00:00<00:10, 19.22it/s]

  5%|▌         | 10/200 [00:00<00:09, 19.83it/s]

  6%|▌         | 12/200 [00:00<00:09, 19.20it/s]

  8%|▊         | 15/200 [00:00<00:09, 20.19it/s]

  9%|▉         | 18/200 [00:00<00:08, 20.91it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:03,  1.25s/candidate]

Evaluating candidates:  86%|████████▌ | 86/100 [00:01<00:00, 87.86candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.19candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 590.73candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 560.50candidate/s]

 10%|█         | 21/200 [00:02<00:40,  4.45it/s]

 12%|█▏        | 24/200 [00:02<00:29,  6.04it/s]

Train MSE: 4.700978844092862e-07
Test MSE: 1953.7899945885868

 14%|█▎        | 27/200 [00:02<00:22,  7.81it/s]

 15%|█▌        | 30/200 [00:03<00:17,  9.72it/s]

 16%|█▋        | 33/200 [00:03<00:14, 11.83it/s]

 18%|█▊        | 36/200 [00:03<00:11, 13.89it/s]

 20%|█▉        | 39/200 [00:03<00:10, 15.60it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:06,  1.28s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.50candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 580.36candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 487.71candidate/s]

 21%|██        | 42/200 [00:05<00:33,  4.70it/s]

Train MSE: 5.658319312651999e-08
Test MSE: 1188.9951570110145

 22%|██▎       | 45/200 [00:05<00:25,  6.18it/s]

 24%|██▍       | 48/200 [00:05<00:19,  7.92it/s]

 26%|██▌       | 51/200 [00:05<00:15,  9.70it/s]

 26%|██▋       | 53/200 [00:05<00:13, 10.95it/s]

 28%|██▊       | 56/200 [00:05<00:11, 12.77it/s]

 30%|██▉       | 59/200 [00:05<00:09, 14.66it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.15s/candidate]

Evaluating candidates:  46%|████▌     | 46/100 [00:01<00:01, 50.30candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.59candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 581.27candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 560.30candidate/s]

 31%|███       | 62/200 [00:07<00:30,  4.52it/s]

Train MSE: 7.45853787526273e-08
Test MSE: 753.9299165457583

 32%|███▎      | 65/200 [00:07<00:22,  5.99it/s]

 34%|███▍      | 68/200 [00:07<00:17,  7.69it/s]

 36%|███▌      | 71/200 [00:07<00:13,  9.52it/s]

 36%|███▋      | 73/200 [00:08<00:11, 10.68it/s]

 38%|███▊      | 76/200 [00:08<00:09, 12.67it/s]

 39%|███▉      | 78/200 [00:08<00:08, 13.83it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.20s/candidate]

Evaluating candidates:  85%|████████▌ | 85/100 [00:01<00:00, 89.51candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.19candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 558.45candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 451.68candidate/s]

 40%|████      | 80/200 [00:09<00:31,  3.83it/s]

 42%|████▏     | 83/200 [00:10<00:21,  5.39it/s]

Train MSE: 4.5042742369109846e-08
Test MSE: 560.0753874870924

 43%|████▎     | 86/200 [00:10<00:15,  7.21it/s]

 44%|████▍     | 88/200 [00:10<00:13,  8.46it/s]

 46%|████▌     | 91/200 [00:10<00:10, 10.42it/s]

 47%|████▋     | 94/200 [00:10<00:08, 12.48it/s]

 48%|████▊     | 97/200 [00:10<00:07, 14.42it/s]

 50%|████▉     | 99/200 [00:10<00:06, 15.24it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates:  55%|█████▌    | 55/100 [00:01<00:00, 58.68candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.91candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  94%|█████████▍| 47/50 [00:00<00:00, 468.97candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 470.96candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 455.25candidate/s]

 50%|█████     | 101/200 [00:12<00:25,  3.81it/s]

 52%|█████▏    | 103/200 [00:12<00:20,  4.80it/s]

Train MSE: 2.255195443083855e-06
Test MSE: 337.9458933320244

 52%|█████▎    | 105/200 [00:12<00:15,  6.04it/s]

 54%|█████▎    | 107/200 [00:12<00:12,  7.46it/s]

 55%|█████▍    | 109/200 [00:13<00:10,  9.06it/s]

 56%|█████▌    | 112/200 [00:13<00:07, 11.64it/s]

 57%|█████▋    | 114/200 [00:13<00:06, 13.09it/s]

 58%|█████▊    | 116/200 [00:13<00:05, 14.43it/s]

 59%|█████▉    | 118/200 [00:13<00:05, 15.63it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:02,  1.24s/candidate]

Evaluating candidates:  74%|███████▍  | 74/100 [00:01<00:00, 76.09candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 71.95candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  92%|█████████▏| 46/50 [00:00<00:00, 456.02candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 451.39candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 376.27candidate/s]

 60%|██████    | 120/200 [00:15<00:23,  3.37it/s]

 61%|██████    | 122/200 [00:15<00:17,  4.43it/s]

Train MSE: 5.3888136717627206e-05
Test MSE: 267.78852575104474

 62%|██████▏   | 124/200 [00:15<00:13,  5.71it/s]

 63%|██████▎   | 126/200 [00:15<00:10,  7.22it/s]

 64%|██████▍   | 128/200 [00:15<00:08,  8.89it/s]

 65%|██████▌   | 130/200 [00:15<00:06, 10.40it/s]

 66%|██████▌   | 132/200 [00:15<00:05, 12.08it/s]

 67%|██████▋   | 134/200 [00:15<00:04, 13.40it/s]

 68%|██████▊   | 136/200 [00:16<00:04, 14.84it/s]

 69%|██████▉   | 138/200 [00:16<00:03, 16.03it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:02,  1.23s/candidate]

Evaluating candidates:  86%|████████▌ | 86/100 [00:01<00:00, 88.60candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.53candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  78%|███████▊  | 39/50 [00:00<00:00, 386.12candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 404.38candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 415.15candidate/s]

 70%|███████   | 140/200 [00:17<00:18,  3.33it/s]

 71%|███████   | 142/200 [00:18<00:13,  4.41it/s]

Train MSE: 2.812230524386189e-06
Test MSE: 233.86862357807362

 72%|███████▏  | 144/200 [00:18<00:09,  5.75it/s]

 73%|███████▎  | 146/200 [00:18<00:07,  7.27it/s]

 74%|███████▍  | 148/200 [00:18<00:05,  8.98it/s]

 76%|███████▌  | 151/200 [00:18<00:04, 11.46it/s]

 76%|███████▋  | 153/200 [00:18<00:03, 12.95it/s]

 78%|███████▊  | 155/200 [00:18<00:03, 13.77it/s]

 78%|███████▊  | 157/200 [00:18<00:02, 15.03it/s]

 80%|███████▉  | 159/200 [00:18<00:02, 15.86it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:00,  1.22s/candidate]

Evaluating candidates:  46%|████▌     | 46/100 [00:01<00:01, 48.01candidate/s]

Evaluating candidates:  94%|█████████▍| 94/100 [00:01<00:00, 104.20candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 69.90candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  80%|████████  | 40/50 [00:00<00:00, 392.30candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 410.91candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 377.20candidate/s]

 80%|████████  | 161/200 [00:20<00:12,  3.22it/s]

 82%|████████▏ | 163/200 [00:20<00:08,  4.26it/s]

Train MSE: 1.4105470751070794e-05
Test MSE: 188.62005988784563

 82%|████████▎ | 165/200 [00:20<00:06,  5.53it/s]

 84%|████████▎ | 167/200 [00:21<00:04,  7.02it/s]

 84%|████████▍ | 169/200 [00:21<00:03,  8.61it/s]

 86%|████████▌ | 171/200 [00:21<00:02, 10.28it/s]

 86%|████████▋ | 173/200 [00:21<00:02, 11.65it/s]

 88%|████████▊ | 175/200 [00:21<00:01, 12.84it/s]

 88%|████████▊ | 177/200 [00:21<00:01, 14.30it/s]

 90%|████████▉ | 179/200 [00:21<00:01, 15.15it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates:   4%|▍         | 4/100 [00:01<00:25,  3.77candidate/s]

Evaluating candidates:  68%|██████▊   | 68/100 [00:01<00:00, 84.61candidate/s]

Evaluating candidates:  98%|█████████▊| 98/100 [00:01<00:00, 117.20candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 64.45candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  42%|████▏     | 21/50 [00:00<00:00, 208.22candidate/s]

Stage 2 candidates:  98%|█████████▊| 49/50 [00:00<00:00, 248.27candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 242.99candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates:  80%|████████  | 20/25 [00:00<00:00, 177.10candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 213.94candidate/s]

 90%|█████████ | 181/200 [00:23<00:06,  2.81it/s]

 92%|█████████▏| 183/200 [00:23<00:04,  3.75it/s]

Train MSE: 0.00036221369176427825
Test MSE: 151.2434123712543

 92%|█████████▎| 185/200 [00:23<00:03,  4.93it/s]

 94%|█████████▎| 187/200 [00:24<00:02,  6.33it/s]

 94%|█████████▍| 189/200 [00:24<00:01,  7.89it/s]

 96%|█████████▌| 191/200 [00:24<00:00,  9.31it/s]

 96%|█████████▋| 193/200 [00:24<00:00, 10.68it/s]

 98%|█████████▊| 195/200 [00:24<00:00, 11.98it/s]

 98%|█████████▊| 197/200 [00:24<00:00, 12.89it/s]

100%|█████████▉| 199/200 [00:24<00:00, 13.66it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:51,  1.12s/candidate]

Evaluating candidates:   4%|▍         | 4/100 [00:01<00:23,  4.13candidate/s]

Evaluating candidates:  54%|█████▍    | 54/100 [00:01<00:00, 70.22candidate/s]

Evaluating candidates:  84%|████████▍ | 84/100 [00:01<00:00, 106.93candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 66.01candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  44%|████▍     | 22/50 [00:00<00:00, 210.06candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 247.48candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 238.60candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates:  92%|█████████▏| 23/25 [00:00<00:00, 217.23candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 228.87candidate/s]

100%|██████████| 200/200 [00:26<00:00,  7.46it/s]

Train MSE: 0.0731375680913975
Test MSE: 128.48926569367472
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...

### Step 8: Visualize Training Progress

Plot the test set MSE over active learning iterations. A decreasing trend indicates the surrogate model is improving. We can also highlight which iterations the GP hyperparameters are re-optimized (vertical gray lines).

In [8]:
plt.plot(sm.training_results["iteration"], sm.training_results["test_mse"])
for ii in range(0, sm.nactive, sm.gp_opt_freq+1):
    plt.axvline(ii, color="gray", linestyle="--", alpha=0.5)
plt.xlabel("Iteration", fontsize=18)
plt.ylabel("Test MSE", fontsize=18)
plt.xlim(0, sm.nactive)
plt.show()

RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error file.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./file.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))

! LaTeX Error: File `type1cm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.7 \usepackage
               {type1ec}^^M
No pages of output.
Transcript written on file.log.

How do the other top initial fits perform during active learning?

In [9]:
al_kwargs = {"algorithm": "bape", 
             "gp_opt_freq": 20, 
             "obj_opt_method": "nelder-mead", 
             "nopt": 6}

mse_results = {}
for idx in top_fits.index:
    gp_kwargs_idx = top_fits[top_fits.index == idx][gp_kwargs.keys()].to_dict(orient="records")[0]
    sm.init_gp(**gp_kwargs_idx, overwrite=True)
    sm.active_train(niter=200, **al_kwargs)
    mse_results[idx] = sm.training_results["test_mse"]

Initialized GP with Matérn-5/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:58,  1.20s/candidate]

Evaluating candidates:  92%|█████████▏| 92/100 [00:01<00:00, 97.75candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.72candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 694.32candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 539.70candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  2%|▏         | 3/200 [00:00<00:10, 18.50it/s]

  3%|▎         | 6/200 [00:00<00:10, 18.53it/s]

  4%|▍         | 8/200 [00:00<00:10, 18.88it/s]

  6%|▌         | 11/200 [00:00<00:09, 19.63it/s]

  7%|▋         | 14/200 [00:00<00:09, 20.30it/s]

  8%|▊         | 17/200 [00:00<00:08, 20.93it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.16s/candidate]

Evaluating candidates:  79%|███████▉  | 79/100 [00:01<00:00, 86.07candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.46candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 605.39candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 563.56candidate/s]

 10%|█         | 20/200 [00:02<00:38,  4.66it/s]

 11%|█         | 22/200 [00:02<00:31,  5.71it/s]

Train MSE: 4.553804085213931e-05
Test MSE: 2142.4873117173406

 12%|█▎        | 25/200 [00:02<00:22,  7.65it/s]

 14%|█▍        | 28/200 [00:02<00:17,  9.72it/s]

 16%|█▌        | 31/200 [00:02<00:14, 11.82it/s]

 17%|█▋        | 34/200 [00:03<00:12, 13.71it/s]

 18%|█▊        | 37/200 [00:03<00:10, 15.41it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates:  55%|█████▌    | 55/100 [00:01<00:00, 58.57candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.44candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 524.49candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 515.27candidate/s]

 20%|██        | 40/200 [00:04<00:35,  4.56it/s]

 22%|██▏       | 43/200 [00:05<00:26,  5.98it/s]

Train MSE: 5.552190947673192e-06
Test MSE: 1287.3844625783286

 23%|██▎       | 46/200 [00:05<00:20,  7.64it/s]

 24%|██▍       | 49/200 [00:05<00:15,  9.48it/s]

 26%|██▌       | 52/200 [00:05<00:12, 11.42it/s]

 28%|██▊       | 55/200 [00:05<00:10, 13.33it/s]

 29%|██▉       | 58/200 [00:05<00:09, 14.92it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:00,  1.21s/candidate]

Evaluating candidates:  96%|█████████▌| 96/100 [00:01<00:00, 100.75candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.86candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 566.80candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 544.73candidate/s]

 30%|███       | 61/200 [00:07<00:29,  4.64it/s]

Train MSE: 5.454812303786748e-07
Test MSE: 773.9095206972922

 32%|███▏      | 64/200 [00:07<00:22,  6.04it/s]

 33%|███▎      | 66/200 [00:07<00:18,  7.13it/s]

 34%|███▍      | 69/200 [00:07<00:14,  9.13it/s]

 36%|███▌      | 72/200 [00:08<00:11, 11.10it/s]

 38%|███▊      | 75/200 [00:08<00:09, 13.15it/s]

 39%|███▉      | 78/200 [00:08<00:08, 14.55it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:51,  1.12s/candidate]

Evaluating candidates:  50%|█████     | 50/100 [00:01<00:00, 56.08candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.59candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 576.40candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 494.05candidate/s]

 40%|████      | 80/200 [00:09<00:28,  4.23it/s]

 41%|████      | 82/200 [00:10<00:22,  5.24it/s]

Train MSE: 2.968805088495862e-07
Test MSE: 685.0707963911882

 42%|████▎     | 85/200 [00:10<00:16,  7.08it/s]

 44%|████▎     | 87/200 [00:10<00:13,  8.38it/s]

 45%|████▌     | 90/200 [00:10<00:10, 10.54it/s]

 46%|████▋     | 93/200 [00:10<00:08, 12.59it/s]

 48%|████▊     | 96/200 [00:10<00:07, 14.50it/s]

 50%|████▉     | 99/200 [00:10<00:06, 15.93it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:50,  1.12s/candidate]

Evaluating candidates:  45%|████▌     | 45/100 [00:01<00:01, 50.56candidate/s]

Evaluating candidates:  96%|█████████▌| 96/100 [00:01<00:00, 114.38candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.40candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  90%|█████████ | 45/50 [00:00<00:00, 445.47candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 464.75candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 444.97candidate/s]

 51%|█████     | 102/200 [00:12<00:21,  4.53it/s]

Train MSE: 2.7848616292170482e-06
Test MSE: 448.0216747543251

 52%|█████▏    | 104/200 [00:12<00:17,  5.49it/s]

 54%|█████▎    | 107/200 [00:12<00:12,  7.18it/s]

 55%|█████▌    | 110/200 [00:13<00:09,  9.05it/s]

 56%|█████▋    | 113/200 [00:13<00:07, 10.92it/s]

 58%|█████▊    | 116/200 [00:13<00:06, 12.91it/s]

 59%|█████▉    | 118/200 [00:13<00:06, 13.64it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:50,  1.12s/candidate]

Evaluating candidates:   2%|▏         | 2/100 [00:01<00:51,  1.92candidate/s]

Evaluating candidates:  84%|████████▍ | 84/100 [00:01<00:00, 115.40candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.81candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  92%|█████████▏| 46/50 [00:00<00:00, 459.36candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 458.20candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 414.84candidate/s]

 60%|██████    | 120/200 [00:15<00:21,  3.79it/s]

 61%|██████    | 122/200 [00:15<00:16,  4.75it/s]

Train MSE: 0.00027723952434785114
Test MSE: 331.49635641198057

 62%|██████▏   | 124/200 [00:15<00:12,  5.95it/s]

 63%|██████▎   | 126/200 [00:15<00:10,  7.32it/s]

 64%|██████▍   | 128/200 [00:15<00:08,  8.86it/s]

 66%|██████▌   | 131/200 [00:15<00:06, 11.21it/s]

 66%|██████▋   | 133/200 [00:15<00:05, 12.57it/s]

 68%|██████▊   | 135/200 [00:15<00:04, 13.85it/s]

 68%|██████▊   | 137/200 [00:16<00:04, 14.77it/s]

 70%|██████▉   | 139/200 [00:16<00:03, 15.57it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.16s/candidate]

Evaluating candidates:  45%|████▌     | 45/100 [00:01<00:01, 48.94candidate/s]

Evaluating candidates:  96%|█████████▌| 96/100 [00:01<00:00, 110.71candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.85candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  82%|████████▏ | 41/50 [00:00<00:00, 404.10candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 418.74candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 412.18candidate/s]

 70%|███████   | 141/200 [00:17<00:17,  3.36it/s]

 72%|███████▏  | 143/200 [00:17<00:12,  4.42it/s]

Train MSE: 0.0003815041789727348
Test MSE: 251.88912071451827

 73%|███████▎  | 146/200 [00:18<00:08,  6.39it/s]

 74%|███████▍  | 148/200 [00:18<00:06,  7.69it/s]

 75%|███████▌  | 150/200 [00:18<00:05,  9.12it/s]

 76%|███████▋  | 153/200 [00:18<00:04, 11.39it/s]

 78%|███████▊  | 155/200 [00:18<00:03, 12.48it/s]

 78%|███████▊  | 157/200 [00:18<00:03, 13.55it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:04,  1.25s/candidate]

Evaluating candidates:  62%|██████▏   | 62/100 [00:01<00:00, 63.09candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 70.16candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  80%|████████  | 40/50 [00:00<00:00, 396.35candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 413.55candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 395.44candidate/s]

 80%|████████  | 160/200 [00:20<00:11,  3.60it/s]

 81%|████████  | 162/200 [00:20<00:08,  4.53it/s]

Train MSE: 0.002027458772164354
Test MSE: 219.1583288431776

 82%|████████▏ | 164/200 [00:20<00:06,  5.71it/s]

 84%|████████▎ | 167/200 [00:20<00:04,  7.76it/s]

 84%|████████▍ | 169/200 [00:21<00:03,  9.11it/s]

 86%|████████▌ | 172/200 [00:21<00:02, 11.31it/s]

 87%|████████▋ | 174/200 [00:21<00:02, 12.47it/s]

 88%|████████▊ | 176/200 [00:21<00:01, 13.30it/s]

 89%|████████▉ | 178/200 [00:21<00:01, 14.14it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:09,  1.31s/candidate]

Evaluating candidates:  75%|███████▌  | 75/100 [00:01<00:00, 73.65candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 67.40candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  52%|█████▏    | 26/50 [00:00<00:00, 238.84candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 277.62candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 245.56candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 239.37candidate/s]

 90%|█████████ | 180/200 [00:23<00:06,  3.05it/s]

 91%|█████████ | 182/200 [00:23<00:04,  3.98it/s]

Train MSE: 8.09283616699066e-05
Test MSE: 184.41121273146078

 92%|█████████▏| 184/200 [00:23<00:03,  5.18it/s]

 93%|█████████▎| 186/200 [00:23<00:02,  6.57it/s]

 94%|█████████▍| 188/200 [00:23<00:01,  8.12it/s]

 95%|█████████▌| 190/200 [00:24<00:01,  9.81it/s]

 96%|█████████▌| 192/200 [00:24<00:00, 11.34it/s]

 97%|█████████▋| 194/200 [00:24<00:00, 12.68it/s]

 98%|█████████▊| 196/200 [00:24<00:00, 13.80it/s]

 99%|█████████▉| 198/200 [00:24<00:00, 14.49it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.18s/candidate]

Evaluating candidates:   6%|▌         | 6/100 [00:01<00:16,  5.74candidate/s]

Evaluating candidates:  82%|████████▏ | 82/100 [00:01<00:00, 100.02candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 66.13candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  48%|████▊     | 24/50 [00:00<00:00, 220.75candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 255.09candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates:  88%|████████▊ | 22/25 [00:00<00:00, 214.33candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 238.89candidate/s]

100%|██████████| 200/200 [00:26<00:00,  2.88it/s]

100%|██████████| 200/200 [00:26<00:00,  7.53it/s]

Train MSE: 8.431502631211932e-05
Test MSE: 154.38253386626045
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...
Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:05,  1.27s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.46candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 604.11candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 532.41candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  1%|          | 2/200 [00:00<00:11, 16.64it/s]

  2%|▏         | 4/200 [00:00<00:10, 18.26it/s]

  4%|▎         | 7/200 [00:00<00:09, 19.85it/s]

  5%|▌         | 10/200 [00:00<00:09, 20.19it/s]

  6%|▋         | 13/200 [00:00<00:08, 20.84it/s]

  8%|▊         | 16/200 [00:00<00:08, 21.10it/s]

 10%|▉         | 19/200 [00:00<00:08, 21.40it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.17s/candidate]

Evaluating candidates:  82%|████████▏ | 82/100 [00:01<00:00, 88.14candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.69candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 646.86candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 563.32candidate/s]

 11%|█         | 22/200 [00:02<00:37,  4.77it/s]

Train MSE: 2.4180145719906228e-08
Test MSE: 1529.8980187995592

 12%|█▎        | 25/200 [00:02<00:27,  6.34it/s]

 14%|█▍        | 28/200 [00:02<00:21,  8.09it/s]

 15%|█▌        | 30/200 [00:02<00:18,  9.24it/s]

 16%|█▋        | 33/200 [00:03<00:14, 11.40it/s]

 18%|█▊        | 36/200 [00:03<00:12, 13.59it/s]

 20%|█▉        | 39/200 [00:03<00:10, 15.48it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.16s/candidate]

Evaluating candidates:  54%|█████▍    | 54/100 [00:01<00:00, 59.02candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.80candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 575.69candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 597.64candidate/s]

 21%|██        | 42/200 [00:05<00:34,  4.60it/s]

Train MSE: 1.4877967080910029e-10
Test MSE: 1265.4765113469984

 22%|██▏       | 44/200 [00:05<00:28,  5.54it/s]

 24%|██▎       | 47/200 [00:05<00:20,  7.31it/s]

 25%|██▌       | 50/200 [00:05<00:16,  9.35it/s]

 26%|██▋       | 53/200 [00:05<00:12, 11.48it/s]

 28%|██▊       | 56/200 [00:05<00:10, 13.58it/s]

 30%|██▉       | 59/200 [00:05<00:09, 15.44it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.13s/candidate]

Evaluating candidates:  52%|█████▏    | 52/100 [00:01<00:00, 57.53candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.41candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 578.09candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 500.89candidate/s]

 31%|███       | 62/200 [00:07<00:29,  4.69it/s]

Train MSE: 2.6775488291029413e-09
Test MSE: 714.00697409893

 32%|███▎      | 65/200 [00:07<00:22,  6.12it/s]

 34%|███▍      | 68/200 [00:07<00:16,  7.82it/s]

 36%|███▌      | 71/200 [00:07<00:13,  9.75it/s]

 37%|███▋      | 74/200 [00:08<00:10, 11.48it/s]

 38%|███▊      | 77/200 [00:08<00:09, 13.22it/s]

 40%|███▉      | 79/200 [00:08<00:08, 14.13it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  70%|███████   | 70/100 [00:01<00:00, 73.73candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.40candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 506.57candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 486.81candidate/s]

 40%|████      | 81/200 [00:09<00:30,  3.89it/s]

Train MSE: 2.382670891013831e-09
Test MSE: 692.9379949659842

 42%|████▏     | 84/200 [00:10<00:21,  5.36it/s]

 43%|████▎     | 86/200 [00:10<00:17,  6.43it/s]

 44%|████▍     | 88/200 [00:10<00:14,  7.76it/s]

 46%|████▌     | 91/200 [00:10<00:10, 10.03it/s]

 47%|████▋     | 94/200 [00:10<00:08, 12.18it/s]

 48%|████▊     | 96/200 [00:10<00:07, 13.30it/s]

 50%|████▉     | 99/200 [00:10<00:06, 15.06it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:01,  1.23s/candidate]

Evaluating candidates:  63%|██████▎   | 63/100 [00:01<00:00, 65.28candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 71.15candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  82%|████████▏ | 41/50 [00:00<00:00, 407.95candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 439.40candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 476.04candidate/s]

 50%|█████     | 101/200 [00:12<00:26,  3.79it/s]

 52%|█████▏    | 104/200 [00:12<00:18,  5.27it/s]

Train MSE: 9.709009263414608e-10
Test MSE: 473.03416437918224

 54%|█████▎    | 107/200 [00:12<00:13,  6.81it/s]

 55%|█████▌    | 110/200 [00:13<00:10,  8.66it/s]

 56%|█████▋    | 113/200 [00:13<00:08, 10.68it/s]

 58%|█████▊    | 116/200 [00:13<00:06, 12.65it/s]

 59%|█████▉    | 118/200 [00:13<00:05, 13.80it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:51,  1.13s/candidate]

Evaluating candidates:  42%|████▏     | 42/100 [00:01<00:01, 46.71candidate/s]

Evaluating candidates:  99%|█████████▉| 99/100 [00:01<00:00, 118.72candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.90candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  78%|███████▊  | 39/50 [00:00<00:00, 383.42candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 404.13candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 403.13candidate/s]

 60%|██████    | 120/200 [00:15<00:21,  3.79it/s]

 61%|██████    | 122/200 [00:15<00:16,  4.78it/s]

Train MSE: 4.931405932089578e-13
Test MSE: 400.7889073836287

 62%|██████▏   | 124/200 [00:15<00:12,  5.98it/s]

 64%|██████▎   | 127/200 [00:15<00:09,  8.10it/s]

 64%|██████▍   | 129/200 [00:15<00:07,  9.55it/s]

 66%|██████▌   | 131/200 [00:15<00:06, 11.11it/s]

 66%|██████▋   | 133/200 [00:15<00:05, 12.33it/s]

 68%|██████▊   | 135/200 [00:15<00:04, 13.41it/s]

 69%|██████▉   | 138/200 [00:16<00:03, 15.55it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:02,  1.24s/candidate]

Evaluating candidates:  78%|███████▊  | 78/100 [00:01<00:00, 80.13candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.25candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  88%|████████▊ | 44/50 [00:00<00:00, 438.99candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 452.39candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 412.96candidate/s]

 70%|███████   | 140/200 [00:17<00:16,  3.62it/s]

 71%|███████   | 142/200 [00:17<00:12,  4.62it/s]

Train MSE: 1.3169511796196124e-08
Test MSE: 260.35702784449785

 72%|███████▏  | 144/200 [00:18<00:09,  5.85it/s]

 73%|███████▎  | 146/200 [00:18<00:07,  7.32it/s]

 74%|███████▍  | 148/200 [00:18<00:05,  8.78it/s]

 75%|███████▌  | 150/200 [00:18<00:04, 10.36it/s]

 76%|███████▌  | 152/200 [00:18<00:04, 11.79it/s]

 77%|███████▋  | 154/200 [00:18<00:03, 12.99it/s]

 78%|███████▊  | 156/200 [00:18<00:03, 14.46it/s]

 79%|███████▉  | 158/200 [00:18<00:02, 15.10it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.17s/candidate]

Evaluating candidates:  48%|████▊     | 48/100 [00:01<00:01, 51.76candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 114.48candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.78candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  78%|███████▊  | 39/50 [00:00<00:00, 383.59candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 411.82candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 387.81candidate/s]

 80%|████████  | 160/200 [00:20<00:12,  3.27it/s]

 81%|████████  | 162/200 [00:20<00:08,  4.30it/s]

Train MSE: 7.777025594348024e-07
Test MSE: 326.65071652911814

 82%|████████▏ | 164/200 [00:20<00:06,  5.52it/s]

 83%|████████▎ | 166/200 [00:20<00:04,  6.92it/s]

 84%|████████▍ | 168/200 [00:21<00:03,  8.36it/s]

 85%|████████▌ | 170/200 [00:21<00:03,  9.83it/s]

 86%|████████▌ | 172/200 [00:21<00:02, 11.28it/s]

 87%|████████▋ | 174/200 [00:21<00:02, 12.44it/s]

 88%|████████▊ | 176/200 [00:21<00:01, 13.65it/s]

 89%|████████▉ | 178/200 [00:21<00:01, 14.84it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.18s/candidate]

Evaluating candidates:   2%|▏         | 2/100 [00:01<00:54,  1.81candidate/s]

Evaluating candidates:  77%|███████▋  | 77/100 [00:01<00:00, 100.35candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 68.64candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  60%|██████    | 30/50 [00:00<00:00, 292.54candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 302.46candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 292.08candidate/s]

 90%|█████████ | 180/200 [00:23<00:06,  3.02it/s]

 91%|█████████ | 182/200 [00:23<00:04,  4.03it/s]

Train MSE: 4.3345086649472637e-13
Test MSE: 420.02664508457764

 92%|█████████▏| 184/200 [00:23<00:03,  5.24it/s]

 93%|█████████▎| 186/200 [00:23<00:02,  6.63it/s]

 94%|█████████▍| 188/200 [00:24<00:01,  8.08it/s]

 95%|█████████▌| 190/200 [00:24<00:01,  9.45it/s]

 96%|█████████▌| 192/200 [00:24<00:00, 10.90it/s]

 97%|█████████▋| 194/200 [00:24<00:00, 12.05it/s]

 98%|█████████▊| 196/200 [00:24<00:00, 13.59it/s]

 99%|█████████▉| 198/200 [00:24<00:00, 14.61it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates:   3%|▎         | 3/100 [00:01<00:35,  2.77candidate/s]

Evaluating candidates:  74%|███████▍  | 74/100 [00:01<00:00, 92.69candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 66.00candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  56%|█████▌    | 28/50 [00:00<00:00, 279.75candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 300.25candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 273.09candidate/s]

100%|██████████| 200/200 [00:26<00:00,  2.89it/s]

100%|██████████| 200/200 [00:26<00:00,  7.52it/s]

Train MSE: 1.444955668584385e-11
Test MSE: 243.6397618977459
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...
Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  78%|███████▊  | 78/100 [00:01<00:00, 81.57candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.66candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 705.70candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 630.59candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  2%|▏         | 3/200 [00:00<00:08, 23.94it/s]

  3%|▎         | 6/200 [00:00<00:08, 23.49it/s]

  4%|▍         | 9/200 [00:00<00:07, 24.11it/s]

  6%|▌         | 12/200 [00:00<00:07, 24.38it/s]

  8%|▊         | 15/200 [00:00<00:07, 23.18it/s]

  9%|▉         | 18/200 [00:00<00:07, 23.29it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  87%|████████▋ | 87/100 [00:01<00:00, 91.06candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 75.24candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 573.20candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 639.86candidate/s]

 10%|█         | 21/200 [00:02<00:37,  4.80it/s]

 12%|█▏        | 24/200 [00:02<00:27,  6.42it/s]

Train MSE: 0.04766057644201889
Test MSE: 2053.7118905296893

 14%|█▎        | 27/200 [00:02<00:20,  8.33it/s]

 15%|█▌        | 30/200 [00:02<00:16, 10.39it/s]

 16%|█▋        | 33/200 [00:02<00:13, 12.50it/s]

 18%|█▊        | 36/200 [00:03<00:11, 14.42it/s]

 20%|█▉        | 39/200 [00:03<00:09, 16.45it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:50,  1.11s/candidate]

Evaluating candidates:   2%|▏         | 2/100 [00:01<00:51,  1.92candidate/s]

Evaluating candidates:  87%|████████▋ | 87/100 [00:01<00:00, 119.48candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.68candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 569.75candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 516.72candidate/s]

 21%|██        | 42/200 [00:04<00:33,  4.77it/s]

 22%|██▎       | 45/200 [00:04<00:24,  6.33it/s]

Train MSE: 0.0012554257443441286
Test MSE: 975.5990042876692

 24%|██▍       | 48/200 [00:05<00:18,  8.04it/s]

 26%|██▌       | 51/200 [00:05<00:14,  9.95it/s]

 27%|██▋       | 54/200 [00:05<00:12, 12.05it/s]

 28%|██▊       | 57/200 [00:05<00:10, 14.23it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.18s/candidate]

Evaluating candidates:  64%|██████▍   | 64/100 [00:01<00:00, 68.36candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.87candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 542.42candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 508.86candidate/s]

 30%|███       | 60/200 [00:07<00:30,  4.64it/s]

 32%|███▏      | 63/200 [00:07<00:22,  6.09it/s]

Train MSE: 0.0002851328725131512
Test MSE: 989.0321820748444

 33%|███▎      | 66/200 [00:07<00:17,  7.83it/s]

 34%|███▍      | 69/200 [00:07<00:13,  9.81it/s]

 36%|███▌      | 72/200 [00:07<00:10, 11.95it/s]

 38%|███▊      | 75/200 [00:07<00:08, 14.22it/s]

 39%|███▉      | 78/200 [00:07<00:07, 16.31it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:04,  1.26s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.64candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 537.13candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 525.83candidate/s]

 40%|████      | 81/200 [00:09<00:25,  4.70it/s]

 42%|████▏     | 84/200 [00:09<00:18,  6.20it/s]

Train MSE: 0.0014465895956752867
Test MSE: 610.7720563741362

 43%|████▎     | 86/200 [00:09<00:15,  7.30it/s]

 44%|████▍     | 89/200 [00:09<00:11,  9.45it/s]

 46%|████▌     | 92/200 [00:10<00:09, 11.70it/s]

 48%|████▊     | 95/200 [00:10<00:07, 13.65it/s]

 49%|████▉     | 98/200 [00:10<00:06, 15.76it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:51,  1.12s/candidate]

Evaluating candidates:   8%|▊         | 8/100 [00:01<00:10,  8.70candidate/s]

Evaluating candidates:  80%|████████  | 80/100 [00:01<00:00, 107.48candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.52candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  90%|█████████ | 45/50 [00:00<00:00, 441.34candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 464.46candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 405.15candidate/s]

 50%|█████     | 101/200 [00:12<00:21,  4.53it/s]

 52%|█████▏    | 104/200 [00:12<00:16,  5.94it/s]

Train MSE: 6.149751590248935e-05
Test MSE: 506.18627481950926

 54%|█████▎    | 107/200 [00:12<00:12,  7.71it/s]

 55%|█████▌    | 110/200 [00:12<00:09,  9.76it/s]

 56%|█████▋    | 113/200 [00:12<00:07, 11.64it/s]

 58%|█████▊    | 116/200 [00:12<00:06, 13.67it/s]

 60%|█████▉    | 119/200 [00:12<00:05, 15.38it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.17s/candidate]

Evaluating candidates:  49%|████▉     | 49/100 [00:01<00:00, 52.72candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.84candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  92%|█████████▏| 46/50 [00:00<00:00, 454.12candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 466.55candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 375.34candidate/s]

 61%|██████    | 122/200 [00:14<00:17,  4.54it/s]

Train MSE: 0.0009893795112390104
Test MSE: 406.6194584994912

 62%|██████▎   | 125/200 [00:14<00:12,  5.98it/s]

 64%|██████▍   | 128/200 [00:14<00:09,  7.61it/s]

 66%|██████▌   | 131/200 [00:15<00:07,  9.42it/s]

 67%|██████▋   | 134/200 [00:15<00:05, 11.34it/s]

 68%|██████▊   | 137/200 [00:15<00:04, 13.30it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.17s/candidate]

Evaluating candidates:   2%|▏         | 2/100 [00:01<00:53,  1.83candidate/s]

Evaluating candidates:  94%|█████████▍| 94/100 [00:01<00:00, 124.35candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 71.99candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  94%|█████████▍| 47/50 [00:00<00:00, 452.30candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 462.24candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 446.25candidate/s]

 70%|███████   | 140/200 [00:17<00:13,  4.38it/s]

 72%|███████▏  | 143/200 [00:17<00:09,  5.74it/s]

Train MSE: 6.719687997387667e-05
Test MSE: 361.3169847220329

 73%|███████▎  | 146/200 [00:17<00:07,  7.37it/s]

 74%|███████▍  | 149/200 [00:17<00:05,  9.09it/s]

 76%|███████▌  | 152/200 [00:17<00:04, 11.05it/s]

 78%|███████▊  | 155/200 [00:17<00:03, 13.03it/s]

 79%|███████▉  | 158/200 [00:17<00:02, 14.82it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.14s/candidate]

Evaluating candidates:  39%|███▉      | 39/100 [00:01<00:01, 43.09candidate/s]

Evaluating candidates:  89%|████████▉ | 89/100 [00:01<00:00, 105.77candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.35candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  80%|████████  | 40/50 [00:00<00:00, 374.86candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 413.96candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 384.70candidate/s]

 80%|████████  | 161/200 [00:19<00:08,  4.44it/s]

 82%|████████▏ | 164/200 [00:19<00:06,  5.83it/s]

Train MSE: 0.01889202092629186
Test MSE: 284.4859870347919

 84%|████████▎ | 167/200 [00:19<00:04,  7.25it/s]

 85%|████████▌ | 170/200 [00:20<00:03,  9.00it/s]

 86%|████████▌ | 172/200 [00:20<00:02, 10.23it/s]

 88%|████████▊ | 175/200 [00:20<00:02, 12.09it/s]

 88%|████████▊ | 177/200 [00:20<00:01, 13.24it/s]

 90%|████████▉ | 179/200 [00:20<00:01, 14.32it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.15s/candidate]

Evaluating candidates:   7%|▋         | 7/100 [00:01<00:12,  7.34candidate/s]

Evaluating candidates:  68%|██████▊   | 68/100 [00:01<00:00, 88.85candidate/s]

Evaluating candidates:  99%|█████████▉| 99/100 [00:01<00:00, 124.33candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 68.46candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  54%|█████▍    | 27/50 [00:00<00:00, 267.97candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 304.71candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 301.40candidate/s]

 90%|█████████ | 181/200 [00:22<00:05,  3.33it/s]

 92%|█████████▏| 183/200 [00:22<00:03,  4.30it/s]

Train MSE: 0.035451614113551314
Test MSE: 245.17351114607044

 93%|█████████▎| 186/200 [00:22<00:02,  6.10it/s]

 94%|█████████▍| 188/200 [00:22<00:01,  7.44it/s]

 96%|█████████▌| 191/200 [00:22<00:00,  9.56it/s]

 96%|█████████▋| 193/200 [00:23<00:00, 10.82it/s]

 98%|█████████▊| 195/200 [00:23<00:00, 12.24it/s]

 98%|█████████▊| 197/200 [00:23<00:00, 13.54it/s]

100%|█████████▉| 199/200 [00:23<00:00, 14.88it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.17s/candidate]

Evaluating candidates:   7%|▋         | 7/100 [00:01<00:14,  6.61candidate/s]

Evaluating candidates:  97%|█████████▋| 97/100 [00:01<00:00, 116.82candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 67.91candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  52%|█████▏    | 26/50 [00:00<00:00, 242.15candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 274.95candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 283.49candidate/s]

100%|██████████| 200/200 [00:25<00:00,  7.91it/s]

Train MSE: 0.02103187410781415
Test MSE: 203.2608910830389
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...
Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:55,  1.16s/candidate]

Evaluating candidates:  70%|███████   | 70/100 [00:01<00:00, 76.15candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.47candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 599.89candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 623.54candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  2%|▏         | 3/200 [00:00<00:09, 19.99it/s]

  3%|▎         | 6/200 [00:00<00:08, 21.91it/s]

  4%|▍         | 9/200 [00:00<00:08, 22.06it/s]

  6%|▌         | 12/200 [00:00<00:08, 22.19it/s]

  8%|▊         | 15/200 [00:00<00:08, 22.48it/s]

  9%|▉         | 18/200 [00:00<00:08, 22.57it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:03,  1.25s/candidate]

Evaluating candidates:  89%|████████▉ | 89/100 [00:01<00:00, 90.81candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 73.15candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 617.18candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 497.74candidate/s]

 10%|█         | 21/200 [00:02<00:38,  4.65it/s]

 12%|█▏        | 23/200 [00:02<00:31,  5.62it/s]

Train MSE: 0.0032137263503993507
Test MSE: 2372.4747714784676

 13%|█▎        | 26/200 [00:02<00:23,  7.53it/s]

 14%|█▍        | 29/200 [00:02<00:17,  9.51it/s]

 16%|█▌        | 32/200 [00:03<00:14, 11.66it/s]

 18%|█▊        | 35/200 [00:03<00:12, 13.62it/s]

 19%|█▉        | 38/200 [00:03<00:10, 15.64it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.15s/candidate]

Evaluating candidates:  77%|███████▋  | 77/100 [00:01<00:00, 84.71candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.60candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 522.64candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 512.65candidate/s]

 20%|██        | 41/200 [00:04<00:33,  4.72it/s]

 22%|██▏       | 44/200 [00:05<00:25,  6.18it/s]

Train MSE: 1.7105195238047145e-06
Test MSE: 1140.2045471341382

 24%|██▎       | 47/200 [00:05<00:19,  7.94it/s]

 25%|██▌       | 50/200 [00:05<00:15,  9.74it/s]

 26%|██▋       | 53/200 [00:05<00:12, 11.74it/s]

 28%|██▊       | 56/200 [00:05<00:10, 13.46it/s]

 30%|██▉       | 59/200 [00:05<00:09, 15.34it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.16s/candidate]

Evaluating candidates:  52%|█████▏    | 52/100 [00:01<00:00, 56.49candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.64candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 599.32candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 513.91candidate/s]

 31%|███       | 62/200 [00:07<00:29,  4.65it/s]

Train MSE: 9.345336173150936e-07
Test MSE: 837.5405879030084

 32%|███▎      | 65/200 [00:07<00:22,  6.09it/s]

 34%|███▍      | 68/200 [00:07<00:17,  7.73it/s]

 36%|███▌      | 71/200 [00:07<00:13,  9.61it/s]

 37%|███▋      | 74/200 [00:08<00:10, 11.60it/s]

 38%|███▊      | 77/200 [00:08<00:09, 13.20it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:50,  1.11s/candidate]

Evaluating candidates:   8%|▊         | 8/100 [00:01<00:11,  8.27candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.99candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 533.68candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 513.72candidate/s]

 40%|████      | 80/200 [00:09<00:25,  4.62it/s]

 41%|████      | 82/200 [00:09<00:21,  5.53it/s]

Train MSE: 1.5410624153289282e-06
Test MSE: 777.8115941651472

 42%|████▎     | 85/200 [00:10<00:15,  7.24it/s]

 44%|████▍     | 88/200 [00:10<00:12,  9.11it/s]

 45%|████▌     | 90/200 [00:10<00:10, 10.33it/s]

 46%|████▋     | 93/200 [00:10<00:08, 12.55it/s]

 48%|████▊     | 96/200 [00:10<00:07, 14.35it/s]

 50%|████▉     | 99/200 [00:10<00:06, 16.17it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:00,  1.22s/candidate]

Evaluating candidates:  64%|██████▍   | 64/100 [00:01<00:00, 66.82candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 71.81candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  96%|█████████▌| 48/50 [00:00<00:00, 472.70candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 475.67candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 403.63candidate/s]

 51%|█████     | 102/200 [00:12<00:22,  4.42it/s]

Train MSE: 1.500035352384098e-06
Test MSE: 515.1013082002805

 52%|█████▏    | 104/200 [00:12<00:17,  5.34it/s]

 54%|█████▎    | 107/200 [00:12<00:13,  7.11it/s]

 55%|█████▍    | 109/200 [00:12<00:10,  8.38it/s]

 56%|█████▌    | 111/200 [00:12<00:09,  9.66it/s]

 57%|█████▋    | 114/200 [00:13<00:07, 12.00it/s]

 58%|█████▊    | 116/200 [00:13<00:06, 13.23it/s]

 60%|█████▉    | 119/200 [00:13<00:05, 15.29it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:06,  1.28s/candidate]

Evaluating candidates:  98%|█████████▊| 98/100 [00:01<00:00, 98.07candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 72.22candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  80%|████████  | 40/50 [00:00<00:00, 390.74candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 427.99candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 409.21candidate/s]

 60%|██████    | 121/200 [00:15<00:20,  3.77it/s]

 62%|██████▏   | 123/200 [00:15<00:16,  4.79it/s]

Train MSE: 0.0028746527736680737
Test MSE: 441.03973337744293

 62%|██████▎   | 125/200 [00:15<00:12,  5.92it/s]

 64%|██████▍   | 128/200 [00:15<00:08,  8.09it/s]

 66%|██████▌   | 131/200 [00:15<00:06, 10.27it/s]

 66%|██████▋   | 133/200 [00:15<00:05, 11.67it/s]

 68%|██████▊   | 135/200 [00:15<00:04, 13.06it/s]

 69%|██████▉   | 138/200 [00:15<00:04, 15.13it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.13s/candidate]

Evaluating candidates:   7%|▋         | 7/100 [00:01<00:12,  7.49candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.96candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  82%|████████▏ | 41/50 [00:00<00:00, 403.07candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 432.84candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 398.42candidate/s]

 70%|███████   | 140/200 [00:17<00:15,  3.79it/s]

 71%|███████   | 142/200 [00:17<00:12,  4.80it/s]

Train MSE: 1.7188147450615795e-06
Test MSE: 289.5543078771144

 72%|███████▏  | 144/200 [00:17<00:09,  6.00it/s]

 73%|███████▎  | 146/200 [00:17<00:07,  7.45it/s]

 74%|███████▍  | 148/200 [00:18<00:05,  8.99it/s]

 75%|███████▌  | 150/200 [00:18<00:04, 10.54it/s]

 76%|███████▌  | 152/200 [00:18<00:03, 12.20it/s]

 78%|███████▊  | 155/200 [00:18<00:03, 14.54it/s]

 78%|███████▊  | 157/200 [00:18<00:02, 15.22it/s]

 80%|███████▉  | 159/200 [00:18<00:02, 16.26it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates:  45%|████▌     | 45/100 [00:01<00:01, 48.05candidate/s]

Evaluating candidates:  91%|█████████ | 91/100 [00:01<00:00, 102.51candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 71.07candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  86%|████████▌ | 43/50 [00:00<00:00, 421.54candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 448.69candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 373.08candidate/s]

 80%|████████  | 161/200 [00:20<00:11,  3.39it/s]

 82%|████████▏ | 163/200 [00:20<00:08,  4.38it/s]

Train MSE: 1.8742298420317561e-06
Test MSE: 270.80984679185354

 82%|████████▎ | 165/200 [00:20<00:06,  5.63it/s]

 84%|████████▎ | 167/200 [00:20<00:04,  7.07it/s]

 84%|████████▍ | 169/200 [00:20<00:03,  8.74it/s]

 86%|████████▌ | 171/200 [00:20<00:02, 10.38it/s]

 86%|████████▋ | 173/200 [00:21<00:02, 11.64it/s]

 88%|████████▊ | 175/200 [00:21<00:01, 13.18it/s]

 88%|████████▊ | 177/200 [00:21<00:01, 14.27it/s]

 90%|████████▉ | 179/200 [00:21<00:01, 15.55it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.20s/candidate]

Evaluating candidates:  38%|███▊      | 38/100 [00:01<00:01, 39.90candidate/s]

Evaluating candidates:  70%|███████   | 70/100 [00:01<00:00, 76.62candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 66.49candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  58%|█████▊    | 29/50 [00:00<00:00, 287.51candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 313.21candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 303.64candidate/s]

 90%|█████████ | 181/200 [00:23<00:06,  2.96it/s]

 92%|█████████▏| 183/200 [00:23<00:04,  3.96it/s]

Train MSE: 1.3916563939108885e-05
Test MSE: 206.43251442175168

 92%|█████████▎| 185/200 [00:23<00:02,  5.16it/s]

 94%|█████████▎| 187/200 [00:23<00:01,  6.55it/s]

 94%|█████████▍| 189/200 [00:23<00:01,  8.04it/s]

 96%|█████████▌| 191/200 [00:23<00:00,  9.61it/s]

 96%|█████████▋| 193/200 [00:24<00:00, 10.81it/s]

 98%|█████████▊| 195/200 [00:24<00:00, 12.14it/s]

 98%|█████████▊| 197/200 [00:24<00:00, 13.32it/s]

100%|█████████▉| 199/200 [00:24<00:00, 14.39it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:   8%|▊         | 8/100 [00:01<00:11,  7.88candidate/s]

Evaluating candidates:  83%|████████▎ | 83/100 [00:01<00:00, 102.30candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 66.73candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  52%|█████▏    | 26/50 [00:00<00:00, 259.58candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 279.86candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 245.73candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 241.06candidate/s]

100%|██████████| 200/200 [00:26<00:00,  7.60it/s]

Train MSE: 7.34190542702686e-05
Test MSE: 182.50843224410045
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...
Initialized GP with Matérn-3/2 kernel.
Successfully initialized GP on attempt 1

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:57,  1.19s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 81.94candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 639.84candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 659.47candidate/s]

Running 200 active learning iterations using bape...

  0%|          | 0/200 [00:00<?, ?it/s]

  1%|          | 2/200 [00:00<00:10, 18.07it/s]

  2%|▏         | 4/200 [00:00<00:10, 18.56it/s]

  3%|▎         | 6/200 [00:00<00:10, 18.12it/s]

  4%|▍         | 8/200 [00:00<00:10, 18.67it/s]

  6%|▌         | 11/200 [00:00<00:08, 21.17it/s]

  7%|▋         | 14/200 [00:00<00:08, 21.93it/s]

  8%|▊         | 17/200 [00:00<00:08, 21.98it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.15s/candidate]

Evaluating candidates:  76%|███████▌  | 76/100 [00:01<00:00, 83.75candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 78.01candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 794.13candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 642.70candidate/s]

 10%|█         | 20/200 [00:02<00:37,  4.76it/s]

 12%|█▏        | 23/200 [00:02<00:27,  6.40it/s]

Train MSE: 2.2934354371468882e-10
Test MSE: 2792.427714164032

 13%|█▎        | 26/200 [00:02<00:20,  8.35it/s]

 14%|█▍        | 29/200 [00:02<00:16, 10.61it/s]

 16%|█▌        | 32/200 [00:02<00:13, 12.65it/s]

 18%|█▊        | 35/200 [00:03<00:11, 14.60it/s]

 19%|█▉        | 38/200 [00:03<00:09, 16.86it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 78.85candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 634.30candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 644.58candidate/s]

 20%|██        | 41/200 [00:04<00:32,  4.95it/s]

 22%|██▏       | 44/200 [00:04<00:24,  6.48it/s]

Train MSE: 1.820482856869029e-10
Test MSE: 2916.411957558519

 24%|██▎       | 47/200 [00:05<00:18,  8.24it/s]

 25%|██▌       | 50/200 [00:05<00:14, 10.20it/s]

 26%|██▋       | 53/200 [00:05<00:12, 12.03it/s]

 28%|██▊       | 56/200 [00:05<00:10, 14.01it/s]

 30%|██▉       | 59/200 [00:05<00:08, 15.92it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:56,  1.18s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 79.32candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 730.57candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 600.23candidate/s]

 31%|███       | 62/200 [00:07<00:27,  4.99it/s]

Train MSE: 1.1903113231153891e-09
Test MSE: 2232.209851837084

 32%|███▎      | 65/200 [00:07<00:20,  6.52it/s]

 34%|███▍      | 68/200 [00:07<00:15,  8.34it/s]

 35%|███▌      | 70/200 [00:07<00:13,  9.55it/s]

 36%|███▋      | 73/200 [00:07<00:10, 11.74it/s]

 38%|███▊      | 76/200 [00:07<00:08, 13.81it/s]

 40%|███▉      | 79/200 [00:07<00:07, 15.37it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:54,  1.16s/candidate]

Evaluating candidates:  77%|███████▋  | 77/100 [00:01<00:00, 83.98candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.90candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 631.88candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 573.33candidate/s]

 41%|████      | 82/200 [00:09<00:25,  4.65it/s]

Train MSE: 4.176463329237382e-09
Test MSE: 2155.176338292105

 42%|████▎     | 85/200 [00:09<00:18,  6.11it/s]

 44%|████▍     | 88/200 [00:09<00:14,  7.87it/s]

 45%|████▌     | 90/200 [00:09<00:12,  9.09it/s]

 46%|████▋     | 93/200 [00:10<00:09, 11.14it/s]

 48%|████▊     | 96/200 [00:10<00:07, 13.25it/s]

 50%|████▉     | 99/200 [00:10<00:06, 14.99it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:00,  1.22s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.01candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 498.06candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 492.30candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 484.31candidate/s]

Train MSE: 1.9020434135621e-17
Test MSE: 2234.232673284284

 51%|█████     | 102/200 [00:12<00:24,  3.96it/s]

 52%|█████▏    | 104/200 [00:12<00:23,  4.17it/s]

 53%|█████▎    | 106/200 [00:13<00:21,  4.34it/s]

 54%|█████▎    | 107/200 [00:13<00:21,  4.40it/s]

 54%|█████▍    | 108/200 [00:13<00:20,  4.39it/s]

 55%|█████▍    | 109/200 [00:13<00:20,  4.46it/s]

 55%|█████▌    | 110/200 [00:14<00:20,  4.46it/s]

 56%|█████▌    | 111/200 [00:14<00:19,  4.54it/s]

 56%|█████▌    | 112/200 [00:14<00:19,  4.58it/s]

 56%|█████▋    | 113/200 [00:14<00:19,  4.50it/s]

 57%|█████▋    | 114/200 [00:14<00:18,  4.72it/s]

 57%|█████▊    | 115/200 [00:15<00:17,  4.80it/s]

 58%|█████▊    | 116/200 [00:15<00:17,  4.85it/s]

 58%|█████▊    | 117/200 [00:15<00:16,  4.98it/s]

 59%|█████▉    | 118/200 [00:15<00:16,  4.84it/s]

 60%|█████▉    | 119/200 [00:15<00:16,  4.97it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:01,  1.22s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.16candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 498.52candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 489.80candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 501.77candidate/s]

 60%|██████    | 120/200 [00:17<00:52,  1.53it/s]

Train MSE: 4.239934982128355e-20
Test MSE: 1498.7561282909005

 60%|██████    | 121/200 [00:17<00:41,  1.90it/s]

 61%|██████    | 122/200 [00:18<00:33,  2.31it/s]

 62%|██████▏   | 123/200 [00:18<00:28,  2.66it/s]

 62%|██████▏   | 124/200 [00:18<00:25,  2.95it/s]

 62%|██████▎   | 125/200 [00:18<00:22,  3.33it/s]

 63%|██████▎   | 126/200 [00:18<00:20,  3.60it/s]

 64%|██████▎   | 127/200 [00:19<00:17,  4.12it/s]

 64%|██████▍   | 128/200 [00:19<00:16,  4.43it/s]

 64%|██████▍   | 129/200 [00:19<00:15,  4.59it/s]

 65%|██████▌   | 130/200 [00:19<00:15,  4.53it/s]

 66%|██████▌   | 131/200 [00:20<00:16,  4.20it/s]

 66%|██████▌   | 132/200 [00:20<00:16,  4.16it/s]

 66%|██████▋   | 133/200 [00:20<00:16,  4.02it/s]

 67%|██████▋   | 134/200 [00:20<00:15,  4.24it/s]

 68%|██████▊   | 135/200 [00:20<00:15,  4.19it/s]

 68%|██████▊   | 136/200 [00:21<00:14,  4.51it/s]

 68%|██████▊   | 137/200 [00:21<00:13,  4.63it/s]

 69%|██████▉   | 138/200 [00:21<00:13,  4.53it/s]

 70%|██████▉   | 139/200 [00:21<00:14,  4.29it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:59,  1.21s/candidate]

Evaluating candidates:  77%|███████▋  | 77/100 [00:01<00:00, 80.99candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 74.38candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  96%|█████████▌| 48/50 [00:00<00:00, 461.94candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 467.16candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 422.35candidate/s]

 70%|███████   | 140/200 [00:23<00:42,  1.42it/s]

Train MSE: 7.4794058806322235e-19
Test MSE: 545.2689656806124

 70%|███████   | 141/200 [00:23<00:32,  1.80it/s]

 71%|███████   | 142/200 [00:24<00:26,  2.17it/s]

 72%|███████▏  | 143/200 [00:24<00:22,  2.59it/s]

 72%|███████▏  | 144/200 [00:24<00:19,  2.90it/s]

 72%|███████▎  | 145/200 [00:24<00:15,  3.46it/s]

 73%|███████▎  | 146/200 [00:24<00:15,  3.53it/s]

 74%|███████▎  | 147/200 [00:25<00:13,  3.81it/s]

 74%|███████▍  | 148/200 [00:25<00:12,  4.01it/s]

 74%|███████▍  | 149/200 [00:25<00:13,  3.85it/s]

 75%|███████▌  | 150/200 [00:25<00:12,  4.00it/s]

 76%|███████▌  | 151/200 [00:26<00:11,  4.23it/s]

 76%|███████▌  | 152/200 [00:26<00:10,  4.42it/s]

 76%|███████▋  | 153/200 [00:26<00:11,  4.25it/s]

 77%|███████▋  | 154/200 [00:26<00:10,  4.49it/s]

 78%|███████▊  | 155/200 [00:26<00:09,  4.98it/s]

 78%|███████▊  | 156/200 [00:27<00:08,  5.01it/s]

 78%|███████▊  | 157/200 [00:27<00:08,  4.88it/s]

 79%|███████▉  | 158/200 [00:27<00:08,  4.68it/s]

 80%|███████▉  | 159/200 [00:27<00:08,  4.97it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<02:03,  1.25s/candidate]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 78.68candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 493.02candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 486.03candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 433.10candidate/s]

 80%|████████  | 160/200 [00:29<00:26,  1.52it/s]

Train MSE: 5.339138973578485e-18
Test MSE: 375.9160730115194

 80%|████████  | 161/200 [00:29<00:20,  1.86it/s]

 81%|████████  | 162/200 [00:30<00:17,  2.18it/s]

 82%|████████▏ | 163/200 [00:30<00:14,  2.59it/s]

 82%|████████▏ | 164/200 [00:30<00:12,  2.86it/s]

 82%|████████▎ | 165/200 [00:30<00:10,  3.27it/s]

 83%|████████▎ | 166/200 [00:30<00:09,  3.67it/s]

 84%|████████▎ | 167/200 [00:31<00:07,  4.22it/s]

 84%|████████▍ | 168/200 [00:31<00:07,  4.40it/s]

 84%|████████▍ | 169/200 [00:31<00:06,  4.56it/s]

 85%|████████▌ | 170/200 [00:31<00:06,  4.51it/s]

 86%|████████▌ | 171/200 [00:31<00:07,  4.13it/s]

 86%|████████▌ | 172/200 [00:32<00:06,  4.04it/s]

 86%|████████▋ | 173/200 [00:32<00:06,  3.89it/s]

 87%|████████▋ | 174/200 [00:32<00:05,  4.43it/s]

 88%|████████▊ | 175/200 [00:32<00:05,  4.50it/s]

 88%|████████▊ | 176/200 [00:33<00:05,  4.37it/s]

 88%|████████▊ | 177/200 [00:33<00:05,  4.42it/s]

 89%|████████▉ | 178/200 [00:33<00:05,  4.21it/s]

 90%|████████▉ | 179/200 [00:33<00:05,  3.97it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:52,  1.14s/candidate]

Evaluating candidates:   4%|▍         | 4/100 [00:01<00:23,  4.09candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 77.44candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  70%|███████   | 35/50 [00:00<00:00, 340.79candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 357.79candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 310.88candidate/s]

 90%|█████████ | 180/200 [00:35<00:14,  1.41it/s]

 90%|█████████ | 181/200 [00:35<00:10,  1.83it/s]

Train MSE: 9.169066644020427e-18
Test MSE: 300.23708295925

 91%|█████████ | 182/200 [00:36<00:08,  2.24it/s]

 92%|█████████▏| 183/200 [00:36<00:06,  2.70it/s]

 92%|█████████▏| 184/200 [00:36<00:05,  3.06it/s]

 92%|█████████▎| 185/200 [00:36<00:04,  3.68it/s]

 93%|█████████▎| 186/200 [00:36<00:03,  4.03it/s]

 94%|█████████▎| 187/200 [00:37<00:03,  3.98it/s]

 94%|█████████▍| 188/200 [00:37<00:02,  4.07it/s]

 94%|█████████▍| 189/200 [00:37<00:02,  4.22it/s]

 95%|█████████▌| 190/200 [00:37<00:02,  4.10it/s]

 96%|█████████▌| 191/200 [00:37<00:02,  4.23it/s]

 96%|█████████▌| 192/200 [00:38<00:01,  4.03it/s]

 96%|█████████▋| 193/200 [00:38<00:01,  4.00it/s]

 97%|█████████▋| 194/200 [00:38<00:01,  4.32it/s]

 98%|█████████▊| 195/200 [00:38<00:01,  4.39it/s]

 98%|█████████▊| 196/200 [00:39<00:00,  4.40it/s]

 98%|█████████▊| 197/200 [00:39<00:00,  4.50it/s]

 99%|█████████▉| 198/200 [00:39<00:00,  4.34it/s]

100%|█████████▉| 199/200 [00:39<00:00,  4.32it/s]

Optimizing GP hyperparameters using 8-fold cross-validation...

Evaluating 100 hyperparameter candidates using 8-fold CV...
Using multiprocessing pool with 8 processes

Evaluating candidates:   0%|          | 0/100 [00:00<?, ?candidate/s]

Evaluating candidates:   1%|          | 1/100 [00:01<01:53,  1.14s/candidate]

Evaluating candidates:  60%|██████    | 60/100 [00:01<00:00, 66.20candidate/s]

Evaluating candidates: 100%|██████████| 100/100 [00:01<00:00, 76.99candidate/s]

Stage 2 candidates:   0%|          | 0/50 [00:00<?, ?candidate/s]

Stage 2 candidates:  60%|██████    | 30/50 [00:00<00:00, 294.53candidate/s]

Stage 2 candidates: 100%|██████████| 50/50 [00:00<00:00, 318.50candidate/s]

Stage 3 candidates:   0%|          | 0/25 [00:00<?, ?candidate/s]

Stage 3 candidates: 100%|██████████| 25/25 [00:00<00:00, 283.97candidate/s]

100%|██████████| 200/200 [00:41<00:00,  1.41it/s]

100%|██████████| 200/200 [00:41<00:00,  4.80it/s]

Train MSE: 1.8418115975059023e-17
Test MSE: 178.92904102359094
Caching model to demo/rosenbrock/ExpSquaredKernel/50_100/surrogate_model...

In [10]:
plt.figure(figsize=(10,6))
for idx in top_fits.index:
    plt.plot(sm.training_results["iteration"], mse_results[idx], label=f"config {idx}")
for ii in range(0, sm.nactive, sm.gp_opt_freq+1):
    plt.axvline(ii, color="gray", linestyle="--", alpha=0.5)
plt.legend(loc="upper right", fontsize=16)
plt.xlabel("Iteration", fontsize=18)
plt.ylabel("Test MSE", fontsize=18)
plt.xlim(0, sm.nactive)
plt.show()

top_fits

RuntimeError: latex was not able to process the following string:
b'lp'

Here is the full command invocation and its output:

latex -interaction=nonstopmode --halt-on-error file.tex

This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./file.tex
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-01-22>
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2023/05/17 v1.4n Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))

! LaTeX Error: File `type1cm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.7 \usepackage
               {type1ec}^^M
No pages of output.
Transcript written on file.log.

,kernel,fit_amp,fit_mean,fit_white_noise,white_noise,gp_opt_method,hyperopt_method,cv_folds,gp_amp_rng,gp_scale_rng,theta_scaler,y_scaler,test_mse
25,Matern52Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),MinMaxScaler(),3014.105741
17,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),StandardScaler(),3085.244354
13,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",MinMaxScaler(),MinMaxScaler(),3262.803131
16,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",StandardScaler(),MinMaxScaler(),3274.704553
9,Matern32Kernel,True,True,False,-12,l-bfgs-b,cv,8,"[-1, 1]","[-2, 2]",no_scaler,no_scaler,3300.396040

### Next Steps

Now that you have an optimized surrogate model, you can:

1. **Run posterior sampling** with `sm.run_emcee()` or `sm.run_dynesty()`
2. **Visualize the surrogate** using `alabi.visualization` tools
3. **Test on new problems** by changing the benchmark function
4. **Expand the hyperparameter grid** to include more options like:
   - Different `white_noise` values
   - Different `cv_folds` settings
   - Different data scaling functions for `theta_scaler` or `y_scaler`